INSERT INTO public.cards (cardid, name, damage, cardtype, element, monstertype) VALUES (8, 'Trockendalf', 8, 'Monster', 'Fire', 'Wizzard');
INSERT INTO public.cards (cardid, name, damage, cardtype, element, monstertype) VALUES (1, 'Goblin Spaeher', 2, 'Monster', 'Normal', 'Goblin');
INSERT INTO public.cards (cardid, name, damage, cardtype, element, monstertype) VALUES (3, 'Sumpf Goblin', 3, 'Monster', 'Water', 'Goblin');
INSERT INTO public.cards (cardid, name, damage, cardtype, element, monstertype) VALUES (2, 'Wuesten Goblin', 4, 'Monster', 'Fire', 'Goblin');
INSERT INTO public.cards (cardid, name, damage, cardtype, element, monstertype) VALUES (5, 'Vulkan Drache', 10, 'Monster', 'Fire', 'Dragon');
INSERT INTO public.cards (cardid, name, damage, cardtype, element, monstertype) VALUES (4, 'Uralter Drache', 12, 'Monster', 'Normal', 'Dragon');
INSERT INTO public.cards (cardid, name, damage, cardtype, element, monstertype) VALUES (6, 'Garados', 9, 'Monster', 'Water', 'Dragon');
INSERT INTO public.cards (cardid, name, damage, cardtype, element, monstertype) VALUES (7, 'Gandalf', 10, 'Monster', 'Normal', 'Wizzard');
INSERT INTO public.cards (cardid, name, damage, cardtype, element, monstertype) VALUES (9, 'Nassdalf', 8, 'Monster', 'Water', 'Wizzard');
INSERT INTO public.cards (cardid, name, damage, cardtype, element, monstertype) VALUES (10, 'Ork Krieger', 6, 'Monster', 'Normal', 'Ork');
INSERT INTO public.cards (cardid, name, damage, cardtype, element, monstertype) VALUES (11, 'Ork Schamane', 6, 'Monster', 'Fire', 'Ork');
INSERT INTO public.cards (cardid, name, damage, cardtype, element, monstertype) VALUES (12, 'Ork Magier', 6, 'Monster', 'Water', 'Ork');
INSERT INTO public.cards (cardid, name, damage, cardtype, element, monstertype) VALUES (13, 'Loyaler Ritter', 5, 'Monster', 'Normal', 'Knight');
INSERT INTO public.cards (cardid, name, damage, cardtype, element, monstertype) VALUES (14, 'Drachen Ritter', 8, 'Monster', 'Fire', 'Knight');
INSERT INTO public.cards (cardid, name, damage, cardtype, element, monstertype) VALUES (15, 'Bruecken Ritter', 3, 'Monster', 'Water', 'Knight');
INSERT INTO public.cards (cardid, name, damage, cardtype, element, monstertype) VALUES (16, 'Kraken', 8, 'Monster', 'Normal', 'Kraken');
INSERT INTO public.cards (cardid, name, damage, cardtype, element, monstertype) VALUES (17, 'Sand Kraken', 6, 'Monster', 'Fire', 'Kraken');
INSERT INTO public.cards (cardid, name, damage, cardtype, element, monstertype) VALUES (19, 'Wald Elf', 2, 'Monster', 'Normal', 'Elf');
INSERT INTO public.cards (cardid, name, damage, cardtype, element, monstertype) VALUES (18, 'Tiefsee Kraken', 10, 'Monster', 'Water', 'Kraken');
INSERT INTO public.cards (cardid, name, damage, cardtype, element, monstertype) VALUES (21, 'Fluss Elf', 2, 'Monster', 'Water', 'Elf');
INSERT INTO public.cards (cardid, name, damage, cardtype, element, monstertype) VALUES (20, 'Vulkan Elf', 3, 'Monster', 'Fire', 'Elf');
INSERT INTO public.cards (cardid, name, damage, cardtype, element, monstertype) VALUES (23, 'Vernichtung', 12, 'Spell', 'Normal', '');
INSERT INTO public.cards (cardid, name, damage, cardtype, element, monstertype) VALUES (22, 'Lebensentzug', 5, 'Spell', 'Normal', '');
INSERT INTO public.cards (cardid, name, damage, cardtype, element, monstertype) VALUES (25, 'Pyroblast', 10, 'Spell', 'Fire', '');
INSERT INTO public.cards (cardid, name, damage, cardtype, element, monstertype) VALUES (24, 'Feuerball', 6, 'Spell', 'Fire', '');
INSERT INTO public.cards (cardid, name, damage, cardtype, element, monstertype) VALUES (26, 'Tropfen', 1, 'Spell', 'Water', '');
INSERT INTO public.cards (cardid, name, damage, cardtype, element, monstertype) VALUES (27, 'Tsunami', 9, 'Spell', 'Water', '');
